# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Update Activity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Update Activity
	pod 'lottie-ios'
	pod 'MaterialComponents/TextFields'
 	pod 'SnapKit', '~> 4.0.0'
  	pod 'Alamofire' ,'~> 4.7'
    pod 'iOSDropDown'
    pod 'Socket.IO-Client-Swift'
    pod 'BubbleTransition', '~> 3.0.0'
  target 'Update ActivityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Update ActivityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
